activation_type:
- relu
batch_size:
- 64
classifier_size:
- medium
drop_out:
- 0.4
hidden_params:
- 512
learning_rate:
- 10e-7
freeze_base_first:
- False
regularization_l1:
- 0.0
regularization_l2:
- 0.0
augmentations:
- False
losses:
  crossentropy:
    name: crossentropy
  focal_loss:
    name: focal_loss
models:
  densenet121:
    classifier:
      in_features: 1024
      key: classifier
    input_size:
    - 224
    - 224
    model_size_(MB): 30.8
    name: densenet121
    num_params: 7978856
    preprocessing:
      crop:
        key: image
        roi:
        - 224
        - 224
      normalize:
        key: image
        means:
        - 0.485
        - 0.456
        - 0.406
        stds:
        - 0.229
        - 0.224
        - 0.225
      resize:
        key: image
        mode: bilinear
        size:
        - 256
        - 256
      scale:
        key: image
        maxv: 1
        minv: 0
    weights: IMAGENET1K_V1
  mobilenet_v2:
    classifier:
      in_features: 1280
      key: classifier
    input_size:
    - 224
    - 224
    model_size_(MB): 13.6
    name: mobilenet_v2
    num_params: 3504872
    preprocessing:
      crop:
        key: image
        roi:
        - 224
        - 224
      normalize:
        key: image
        means:
        - 0.485
        - 0.456
        - 0.406
        stds:
        - 0.229
        - 0.224
        - 0.225
      resize:
        key: image
        mode: bilinear
        size:
        - 256
        - 256
      scale:
        key: image
        maxv: 1
        minv: 0
    weights: IMAGENET1K_V1
  efficientnet_b0:
    classifier:
      in_features: 1280
      key: classifier
    input_size:
    - 224
    - 224
    model_size_(MB): 20.5
    name: efficientnet_b0
    num_params: 5288548
    preprocessing:
      crop:
        key: image
        roi:
        - 224
        - 224
      normalize:
        key: image
        means:
        - 0.485
        - 0.456
        - 0.406
        stds:
        - 0.229
        - 0.224
        - 0.225
      resize:
        key: image
        mode: bicubic
        size:
        - 256
        - 256
      scale:
        key: image
        maxv: 1
        minv: 0
    weights: IMAGENET1K_V1
  resnet18:
    classifier:
      in_features: 512
      key: fc
    input_size:
    - 224
    - 224
    model_size_(MB): 44.7
    name: resnet18
    num_params: 11689512
    preprocessing:
      crop:
        key: image
        roi:
        - 224
        - 224
      normalize:
        key: image
        means:
        - 0.485
        - 0.456
        - 0.406
        stds:
        - 0.229
        - 0.224
        - 0.225
      resize:
        key: image
        mode: bilinear
        size:
        - 256
        - 256
      scale:
        key: image
        maxv: 1
        minv: 0
    weights: IMAGENET1K_V1
  maxvit_t:
    classifier:
      in_features: 25088
      key: medium_flatten
    input_size:
    - 224
    - 224
    model_size_(MB): 108.2
    name: maxvit_t
    num_params: 28351570
    preprocessing:
      crop:
        key: image
        roi:
        - 224
        - 224
      normalize:
        key: image
        means:
        - 0.485
        - 0.456
        - 0.406
        stds:
        - 0.229
        - 0.224
        - 0.225
      resize:
        key: image
        mode: bicubic
        size:
        - 256
        - 256
      scale:
        key: image
        maxv: 1
        minv: 0
    weights: IMAGENET1K_V1
  vgg16:
    classifier:
      in_features: 25088
      key: classifier
    input_size:
    - 224
    - 224
    model_size_(MB): 527.8
    name: vgg16
    num_params: 138357544
    preprocessing:
      crop:
        key: image
        roi:
        - 224
        - 224
      normalize:
        key: image
        means:
        - 0.485
        - 0.456
        - 0.406
        stds:
        - 0.229
        - 0.224
        - 0.225
      resize:
        key: image
        mode: bilinear
        size:
        - 256
        - 256
      scale:
        key: image
        maxv: 1
        minv: 0
    weights: IMAGENET1K_V1
optimizer:
  adamw:
    name: adamw
    weight_decay: 1.0e-05
  sgd:
      name: sgd
      weight_decay: 1.0e-05
